### ISSUE TITLE
Container has wrong mamba version

### ISSUE THREAD

**Issue by zdk123** [mamba-org/micromamba-docker#7] opened 2021-02-18 18:58 UTC
Reproduce with:
```sh
docker pull mambaorg/micromamba:0.7.14
docker run mambaorg/micromamba:0.7.14 mamba --version
# 0.7.13
```

**Comment by wholtz** [comment] 2021-02-20 01:28
Hi @zdk123, thanks for pointing this out and for the PR. There were a few other places in the repo where the version number needed to be updated in the documentation (see update.sh), so I didn't use your PR. The issue is fixed in 29d3859d6680b9931ef5cbe79c4631e5dc6860ae. It will take up to 6 hours for the builds on dockerhub to be updated.  Our automatic build process needs to be altered or this same problem will happen again the next time micromamba has a new version released. I am making a new issue  (#9) to track the problem with the automatic builds.

**Closed by wholtz** 2021-02-20 01:28 UTC
