### ISSUE TITLE
_dockerfile_shell.sh python Doesn't Work

### ISSUE THREAD

**Issue by zN3utr4l** [mamba-org/micromamba-docker#301] opened 2023-05-02 08:54 UTC
_Issue-like bug_ https://github.com/mamba-org/micromamba-docker/issues/278
https://github.com/mamba-org/micromamba-docker/issues/278#issuecomment-1473965871 doesn't fix

**Error 1:**

```
=> ERROR [service-test-stage 6/6] RUN python manage.py test */tests/unit/                                                                                                                             0.3s 
------
> [service-test-stage 6/6] RUN python manage.py test */tests/unit/:
#0 0.326 bash: line 1: python: command not found
------
failed to solve: executor failed running [/usr/local/bin/_dockerfile_shell.sh python manage.py test */tests/unit/]: exit code: 127
```

**Error 2:**
```
 => ERROR [stage-2 5/8] RUN micromamba remove -f -y pytest pytest-django locust model-bakery pandera                                                                                                   0.4s
------
 > [stage-2 5/8] RUN micromamba remove -f -y pytest pytest-django locust model-bakery pandera:
#0 0.421
#0 0.421                                            __
#0 0.421           __  ______ ___  ____ _____ ___  / /_  ____ _
#0 0.421          / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
#0 0.421         / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
#0 0.421        / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
#0 0.421       /_/
#0 0.421
#0 0.422 error    libmamba Could not find packages to remove:
#0 0.422      - pytest
#0 0.422      - pytest-django
#0 0.422      - locust
#0 0.422      - model-bakery
#0 0.422      - pandera
#0 0.422
#0 0.422 critical libmamba Could not find packages to remove:
#0 0.422      - pytest
#0 0.422      - pytest-django
#0 0.422      - locust
#0 0.422      - model-bakery
#0 0.422      - pandera
------
failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba remove -f -y pytest pytest-django locust model-bakery pandera" did not complete successfully: exit code: 1
```

**Dockerfile**
```
FROM mambaorg/micromamba:1.4.2-alpine as service-middle-stage

ARG ENV_FILE_PROD=environment.linux.prod.yml
ARG PIP_DEFAULT_TIMEOUT=5000

COPY --chown=$MAMBA_USER:$MAMBA_USER ./Analyser/${ENV_FILE_PROD} /tmp

RUN --mount=type=cache,target=$MAMBA_ROOT_PREFIX/pkgs --mount=type=cache,target=/root/.cache \
    micromamba config set auto_activate_base false && \
    micromamba create -y -f /tmp/${ENV_FILE_PROD} \
    && find -name '*.a' -delete \
    && rm -rf $MAMBA_ROOT_PREFIX/envs/conda-meta \
    && rm -rf $MAMBA_ROOT_PREFIX/envs/include \
    && find -name '__pycache__' -type d -exec rm -rf '{}' '+' \
    && rm -rf $MAMBA_ROOT_PREFIX/envs/lib/python3.8/site-packages/pip \
    $MAMBA_ROOT_PREFIX/envs/lib/python3.8/idlelib \
    $MAMBA_ROOT_PREFIX/envs/lib/python3.8/ensurepip \
    $MAMBA_ROOT_PREFIX/envs/lib/libasan.so.5.0.0 \
    $MAMBA_ROOT_PREFIX/envs/lib/libtsan.so.0.0.0 \
    $MAMBA_ROOT_PREFIX/envs/lib/liblsan.so.0.0.0 \
    $MAMBA_ROOT_PREFIX/envs/lib/libubsan.so.1.0.0 \
    $MAMBA_ROOT_PREFIX/envs/bin/x86_64-conda-linux-gnu-ld \
    $MAMBA_ROOT_PREFIX/envs/bin/sqlite3 \
    $MAMBA_ROOT_PREFIX/envs/bin/openssl \
    $MAMBA_ROOT_PREFIX/envs/share/terminfo \
    && micromamba clean --all --yes

USER root

COPY ./Docker/Service/docker-entrypoint.sh /usr/local/bin

RUN apk add --no-cache dos2unix \
    && dos2unix /usr/local/bin/docker-entrypoint.sh \
    && chmod 777 /usr/local/bin/docker-entrypoint.sh 


FROM mambaorg/micromamba:1.4.2-alpine as service-test-stage

ARG MAMBA_DOCKERFILE_ACTIVATE=1

COPY --chown=$MAMBA_USER:$MAMBA_USER --from=service-middle-stage $MAMBA_ROOT_PREFIX/envs $MAMBA_ROOT_PREFIX/envs
COPY --chown=$MAMBA_USER:$MAMBA_USER --from=service-middle-stage /usr/local/bin/docker-entrypoint.sh /usr/local/bin

WORKDIR /code

COPY --chown=$MAMBA_USER:$MAMBA_USER ./Analyser ./Analyser

RUN python manage.py test */tests/unit/    <------------------- #ERROR LINE


FROM mambaorg/micromamba:1.4.2-alpine

LABEL description="Service image" version="v1.4.2-alpine"

USER root

RUN apk add --no-cache curl

USER $MAMBA_USER

ARG MAMBA_DOCKERFILE_ACTIVATE=1

COPY --chown=$MAMBA_USER:$MAMBA_USER --from=service-middle-stage $MAMBA_ROOT_PREFIX/envs $MAMBA_ROOT_PREFIX/envs
COPY --chown=$MAMBA_USER:$MAMBA_USER --from=service-middle-stage /usr/local/bin/docker-entrypoint.sh /usr/local/bin

RUN micromamba remove --force pytest pytest-django locust model-bakery pandera  <------------------- #ERROR LINE

WORKDIR /code

COPY --chown=$MAMBA_USER:$MAMBA_USER ./Analyser ./Analyser

RUN find -name "tests" -type d -exec rm -rf '{}' '+' \
    && find -name '__pycache__' -type d -exec rm -rf '{}' '+' \
    && find -name '*.test_*.py' -delete \
    && rm -rf .pytest_cache

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 7000
```

ENV.yml:
```
name: production
channels:
  - conda-forge
dependencies:
  - setuptools
  - psycopg2
  - markdown
  - plotly
  - pika
  - orca
  - python-kaleido
  - pip
  - pydantic
  - openpyxl
  - tensorflow-cpu=2.11.1
  - scikit-learn
  - events
  - ruptures
  - fontconfig
  - weasyprint
  - argon2-cffi
  - pillow
  - psutil
  - nest-asyncio
  - python=3.9
  - pip:
    - djoser
    - celery
    - django-celery-beat
    - django-celery-results
    - django-pgviews-redux
    - django-etc
    - django-filter
    - django-debug-toolbar
    - django-tastypie
    - django-cors-headers
    - djangorestframework-simplejwt
    - django-admin-interface
    - django-admin-autocomplete-all
    - django-split-settings
    - django-health-check
    - django-phonenumber-field[phonenumbers]
    - cryptography
    - django-jsonform
    - django-object-actions
    - django-timescaledb
    - Cython
    - validx
    - gunicorn
    # - uvicorn
    # - certbot-nginx
    - pytest
    - pytest-django
    - locust
    - model-bakery
    - pandera
    - --extra-index-url https://Test:Test@pkgs.dev.azure.com/Test/_packaging/Test/pypi/simple/ 
    - test-scheduled-maintenance
```

**Comment by zN3utr4l** [comment] 2023-05-02 10:15
https://github.com/mamba-org/micromamba-docker/issues/267#issuecomment-1448959684 **this workaround doesn't work**
``` 
version: "3.9"
services:
     analyser:
          image: costal/analyser:v1.4.2-alpine
          build:
              context: ../
              dockerfile: ./Docker/Service/Dockerfile
          ulimits:
              nofile:
                  soft: "65536"
                  hard: "65536"
        ..............
```

**Comment by wholtz** [comment] 2023-05-02 14:57
Hi @zN3utr4l . Thank you for your interest in micromamba and for taking the time to submit an issue. 

Your Dockerfile and environement are rather large. Have you attempted to make a minimal reproduction of the error?

I tried to reproduce your error, but I'm missing the file `./Docker/Service/docker-entrypoint.sh`. I'm also making the assumption that your build command was something like:

```
docker build . -t my_tag:1 --build-arg ENV_FILE_PROD=ENV.yml
```

Please let me know if that is correct.

**Comment by zN3utr4l** [comment] 2023-05-03 06:19
Hi @wholtz, thanks for the reply.
Now I try to reproduce the error in a more restricted case.
Below is the requested information

**Command:**
`docker compose -f docker-compose.yml --env-file .env -p analyser up --build -d analyser`

**Entrypoint:**
```
#!/usr/bin/env bash

set -o nounset

cd Analyser
if [ -e environment.linux.prod.yml ] && [ -e environment.linux.yml ]; then
    rm -f environment.linux.prod.yml environment.linux.yml
fi

path=$( echo ${DJANGO_DIR_LOG%/*} )
file=$( echo ${DJANGO_DIR_LOG##*/} )
mkdir -p /run/gunicorn $path/gunicorn # $path/nginx
chmod -R 777 $path media/
chown -R $MAMBA_USER:$MAMBA_USER $path media/ /code/Certs/*/client /code/Certs/*/testca

FILE=/run/gunicorn/gunicorn.pid
if [ -f "$FILE" ]; then
    echo "$FILE already exists"
    rm -f $FILE
fi

if [ ! -z ${BEAT_ON:-} ];
then
    BEAT_ON_LOWER=$(echo $BEAT_ON | tr '[:upper:]' '[:lower:]')
    if [[ "$BEAT_ON_LOWER" == "true" || "$BEAT_ON_LOWER" == "t" || "$BEAT_ON_LOWER" == "y" || "$BEAT_ON_LOWER" == "yes" ]]
    then
        echo "START BEAT"

        celery -A scheduler.celery beat -l INFO --uid=nobody --gid=nogroup --detach

        if [ $? -eq 0 ]; then
            echo "BEAT STARTED"
        else
            echo "RETRY IN FEW SECONDS"
            exit 1
        fi
    fi
fi

if [ ! -z ${WORKER_ON:-} ];
then
    WORKER_ON_LOWER=$(echo $WORKER_ON | tr '[:upper:]' '[:lower:]')
    if [[ "$WORKER_ON_LOWER" == "true" || "$WORKER_ON_LOWER" == "t" || "$WORKER_ON_LOWER" == "y" || "$WORKER_ON_LOWER" == "yes" ]]
    then
        echo "START WORKER"

        celery -A scheduler.celery worker -l INFO -E --uid=nobody --gid=nogroup -O fair --hostname=celery-workerAnalyser # --detach

        if [ $? -eq 0 ]; then
            echo "WORKER STARTED"
        else
            echo "RETRY IN FEW SECONDS"
            exit 1
        fi
    fi
fi

echo "Collect static files"
python manage.py collectstatic --noinput --clear
if [ $? -eq 0 ]; then
    echo "Finish Collect static"
else
    echo "RETRY IN FEW SECONDS"
    exit 1
fi

# region Solo al primo build

MIGRATIONNAME="group_level"

if python manage.py showmigrations auth | grep -q MIGRATIONNAME; then
    echo "Auth Migration already installed" 
else
    python manage.py makemigrations auth --name group_level

    if [ $? -eq 0 ]; then
        echo "Finish Makemigrations"
    else
        echo "Can\'t create migrations for group levels"
    fi
fi

#endregion

echo "Run Migrate for chache table"
python manage.py createcachetable

echo "Run Migrate for analyser"
python manage.py migrate --database default
if [ $? -eq 0 ]; then
    echo "Finish Migrate"
else
    echo "RETRY IN FEW SECONDS"
    exit 1
fi

echo "Run Migrate for collector"
python manage.py migrate --database collector
if [ $? -eq 0 ]; then
    echo "Finish Migrate"
else
    echo "RETRY IN FEW SECONDS"
    exit 1
fi

if [[ -n "$DJANGO_SUPERUSER_USERNAME" ]]
then
    python manage.py createsuperuser --no-input
fi

# nginx

# python manage.py runserver 0.0.0.0:7000 --noreload

gunicorn

if [ $? -eq 0 ]; then
    echo "Start Server"
else
    echo "RETRY IN FEW SECONDS"
    exit 1
fi


exec "$@"
```

**Comment by zN3utr4l** [comment] 2023-05-03 07:13
**environment.linux.prod.sh:**
```
name: production
channels:
  - conda-forge
dependencies:
  - psycopg2
  - pip
  - python=3.9
  - pip:
    - django
    - pytest
    - pytest-django
    - locust
    - model-bakery
    - pandera
```

**Dockerfile:**
```
FROM mambaorg/micromamba:1.4.2-alpine as service-middle-stage

ARG ENV_FILE_PROD=environment.linux.prod.yml
ARG PIP_DEFAULT_TIMEOUT=5000

COPY --chown=$MAMBA_USER:$MAMBA_USER ./Analyser/${ENV_FILE_PROD} /tmp

RUN --mount=type=cache,target=$MAMBA_ROOT_PREFIX/pkgs --mount=type=cache,target=/root/.cache \
    micromamba config set auto_activate_base false && \
    micromamba create -y -f /tmp/${ENV_FILE_PROD} \
    && find -name '*.a' -delete \
    && rm -rf $MAMBA_ROOT_PREFIX/envs/conda-meta \
    && rm -rf $MAMBA_ROOT_PREFIX/envs/include \
    && find -name '__pycache__' -type d -exec rm -rf '{}' '+' \
    && rm -rf $MAMBA_ROOT_PREFIX/envs/lib/*/site-packages/pip \
    $MAMBA_ROOT_PREFIX/envs/lib/*/idlelib \
    $MAMBA_ROOT_PREFIX/envs/lib/*/ensurepip \
    $MAMBA_ROOT_PREFIX/envs/lib/libasan.so* \
    $MAMBA_ROOT_PREFIX/envs/lib/libtsan.so* \
    $MAMBA_ROOT_PREFIX/envs/lib/liblsan.so* \
    $MAMBA_ROOT_PREFIX/envs/lib/libubsan.so*\
    $MAMBA_ROOT_PREFIX/envs/bin/*-conda-linux-gnu-ld \
    $MAMBA_ROOT_PREFIX/envs/bin/sqlite3 \
    $MAMBA_ROOT_PREFIX/envs/bin/openssl \
    $MAMBA_ROOT_PREFIX/envs/share/terminfo \
    && micromamba clean --all --yes

USER root

COPY ./Docker/Service/docker-entrypoint.sh /usr/local/bin

RUN apk add --no-cache dos2unix \
    && dos2unix /usr/local/bin/docker-entrypoint.sh \
    && chmod 777 /usr/local/bin/docker-entrypoint.sh 


FROM mambaorg/micromamba:1.4.2-alpine as service-test-stage

ARG MAMBA_DOCKERFILE_ACTIVATE=1

COPY --chown=$MAMBA_USER:$MAMBA_USER --from=service-middle-stage $MAMBA_ROOT_PREFIX/envs $MAMBA_ROOT_PREFIX/envs
COPY --chown=$MAMBA_USER:$MAMBA_USER --from=service-middle-stage /usr/local/bin/docker-entrypoint.sh /usr/local/bin

WORKDIR /code

COPY --chown=$MAMBA_USER:$MAMBA_USER ./Analyser ./Analyser

RUN python manage.py test */tests/unit/

RUN micromamba remove -f -y pytest pytest-django locust model-bakery pandera

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]
```

**docker-compose.yml:**
```
version: "3.9"

services:
    analyser:
        image: costal/analyser:v1.4.2-alpine
        build:
            context: ../
            dockerfile: ./Docker/Service/Dockerfile
        logging:
            driver: "json-file"
            options:
                max-file: "6"
                max-size: 1024m
        container_name: analyser
        environment:
            - ENV_NAME=production
        hostname: hostAnalyser
        user: root
        restart: always
        mem_limit: 5120m
        mem_reservation: 1024m
```

**Command:**
`docker compose -f docker-compose.dev.yml -p analyser up --build -d analyser`

**My output:**
```
(base) PS D:\Repository\Analysis Detection\Costal.DataAnalyser\Docker> docker compose -f docker-compose.dev.yml  -p analyser up --build -d analyser
[+] Building 1.7s (14/15)
 => [internal] load build definition from Dockerfile                                                                                                                                                    0.0s
 => => transferring dockerfile: 3.68kB                                                                                                                                                                  0.0s 
 => [internal] load .dockerignore                                                                                                                                                                       0.0s 
 => => transferring context: 393B                                                                                                                                                                       0.0s 
 => [internal] load metadata for docker.io/mambaorg/micromamba:1.4.2-alpine                                                                                                                             0.9s 
 => [internal] load build context                                                                                                                                                                       0.3s
 => => transferring context: 103.90kB                                                                                                                                                                   0.3s 
 => [service-middle-stage 1/5] FROM docker.io/mambaorg/micromamba:1.4.2-alpine@sha256:d95a239d97da7cc14090742e33bf89382299a593434563222f4b092c74b53725                                                  0.0s 
 => CACHED [service-middle-stage 2/5] COPY --chown=mambauser:mambauser ./Analyser/environment.linux.prod.yml /tmp                                                                                       0.0s
 => CACHED [service-middle-stage 3/5] RUN --mount=type=cache,target=/opt/conda/pkgs --mount=type=cache,target=/root/.cache     micromamba config set auto_activate_base false &&     micromamba create  0.0s 
 => CACHED [service-middle-stage 4/5] COPY ./Docker/Service/docker-entrypoint.sh /usr/local/bin                                                                                                         0.0s 
 => CACHED [service-middle-stage 5/5] RUN apk add --no-cache dos2unix     && dos2unix /usr/local/bin/docker-entrypoint.sh     && chmod 777 /usr/local/bin/docker-entrypoint.sh                          0.0s 
 => CACHED [service-test-stage 2/7] COPY --chown=mambauser:mambauser --from=service-middle-stage /opt/conda/envs /opt/conda/envs                                                                        0.0s 
 => CACHED [service-test-stage 3/7] COPY --chown=mambauser:mambauser --from=service-middle-stage /usr/local/bin/docker-entrypoint.sh /usr/local/bin                                                     0.0s 
 => CACHED [service-test-stage 4/7] WORKDIR /code                                                                                                                                                       0.0s 
 => CACHED [service-test-stage 5/7] COPY --chown=mambauser:mambauser ./Analyser ./Analyser                                                                                                              0.0s 
 => ERROR [service-test-stage 6/7] RUN python manage.py test */tests/unit/                                                                                                                              0.5s 
------
 > [service-test-stage 6/7] RUN python manage.py test */tests/unit/:
#0 0.444 bash: line 1: python: command not found
------
failed to solve: process "/usr/local/bin/_dockerfile_shell.sh python manage.py test */tests/unit/" did not complete successfully: exit code: 127
```

**Comment by zN3utr4l** [comment] 2023-05-03 10:03
Hi @maresb, Do you think it's okay now?

**Dockerfile:**
```
FROM mambaorg/micromamba:1.4.2-alpine as service-middle-stage

RUN echo $'\
name: production\n\
channels:\n\
    - conda-forge\n\
dependencies:\n\
    - pip\n\
    - python=3.8\n\
    - pip:\n\
        - django' >> /tmp/environment.yml \
    \
    && echo $"print('working')" >> main.py

ARG PIP_DEFAULT_TIMEOUT=5000
ARG MAMBA_DOCKERFILE_ACTIVATE=1

RUN micromamba create -y -f /tmp/environment.yml
RUN python main.py
RUN micromamba remove -f -y django
```

**Command:**
`docker build --no-cache -t test-f Dockerfile`

**My output:**
```
(base) PS D:\Repository\Analysis Detection\Costal.DataAnalyser\Docker> docker build --no-cache -t analyser_test -f Service/Dockerfile ../
[+] Building 34.6s (7/8)
 => [internal] load build definition from Dockerfile                                                                                                                                                    0.1s
 => => transferring dockerfile: 511B                                                                                                                                                                    0.0s 
 => [internal] load .dockerignore                                                                                                                                                                       0.0s 
 => => transferring context: 393B                                                                                                                                                                       0.0s 
 => [internal] load metadata for docker.io/mambaorg/micromamba:1.4.2-alpine                                                                                                                             0.5s
 => CACHED [1/5] FROM docker.io/mambaorg/micromamba:1.4.2-alpine@sha256:d95a239d97da7cc14090742e33bf89382299a593434563222f4b092c74b53725                                                                0.0s
 => [2/5] RUN echo $'name: production\nchannels:\n    - conda-forge\ndependencies:\n    - pip\n    - python=3.8\n    - pip:\n        - django' >> /tmp/environment.yml         && echo $"print('workin  0.4s 
 => [3/5] RUN micromamba create -y -f /tmp/environment.yml                                                                                                                                             33.1s
 => ERROR [4/5] RUN python main.py                                                                                                                                                                      0.5s
------
 > [4/5] RUN python main.py:
#0 0.499 bash: line 1: python: command not found
------
Dockerfile:19
--------------------
  17 |
  18 |     RUN micromamba create -y -f /tmp/environment.yml
  19 | >>> RUN python main.py
  20 |     RUN micromamba remove -f -y django
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh python main.py" did not complete successfully: exit code: 127
```

**Comment by maresb** [comment] 2023-05-03 10:23
Hi @zN3utr4l, yes, that's exactly what I needed to be able to help you out.

Rather than creating a new environment called `production` I'd recommend you use the existing base environment. In particular, see the following comment lines in the "Quick start" example:

```yaml
# Using an environment name other than "base" is not recommended!
# Read https://github.com/mamba-org/micromamba-docker#multiple-environments
# if you must use a different environment name.
```

It can be fixed with two modifications. First, modify `environment.yml` to have `name: base` instead of `name: production`. Second, switch the `micromamba create` line to `RUN micromamba install -y -n base -f /tmp/environment.yml`.

**Comment by zN3utr4l** [comment] 2023-05-03 11:49
Thanks for the reply, `RUN python main.py` runs fine, but micromamba remove doesn't, I need to run some other command pre remove? 
Also if I wanted to create the env in one image and copy it to another, like in this my dockerfile https://github.com/mamba-org/micromamba-docker/issues/301#issuecomment-1532557804 to reduce the size of the image, how should I do?

```
(base) PS D:\Repository\Analysis Detection\Costal.DataAnalyser\Docker> docker build --no-cache -t analyser_test -f Service/Dockerfile.https ../
[+] Building 32.5s (8/8) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                       0.1s
 => => transferring context: 393B                                                                                                                                                                       0.0s 
 => [internal] load build definition from Dockerfile.https                                                                                                                                              0.1s 
 => => transferring dockerfile: 519B                                                                                                                                                                    0.0s 
 => [internal] load metadata for docker.io/mambaorg/micromamba:1.4.2-alpine                                                                                                                             1.2s
 => CACHED [1/5] FROM docker.io/mambaorg/micromamba:1.4.2-alpine@sha256:d95a239d97da7cc14090742e33bf89382299a593434563222f4b092c74b53725                                                                0.0s
 => [2/5] RUN echo $'name: base\nchannels:\n    - conda-forge\ndependencies:\n    - pip\n    - python=3.8\n    - pip:\n        - django' >> /tmp/environment.yml         && echo $"print('working')" >  0.4s 
 => [3/5] RUN micromamba install -y -n base -f /tmp/environment.yml                                                                                                                                    29.8s
 => [4/5] RUN python main.py                                                                                                                                                                            0.4s
 => ERROR [5/5] RUN micromamba remove -f -y django                                                                                                                                                      0.6s
------
 > [5/5] RUN micromamba remove -f -y django:
#0 0.505
#0 0.505                                            __
#0 0.505           __  ______ ___  ____ _____ ___  / /_  ____ _
#0 0.505          / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
#0 0.505         / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
#0 0.505        / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
#0 0.505       /_/
#0 0.505
#0 0.545 error    libmamba Could not find packages to remove:
#0 0.545      - django
#0 0.545
#0 0.546 critical libmamba Could not find packages to remove:
#0 0.546      - django
------
Dockerfile.https:20
--------------------
  18 |     RUN micromamba install -y -n base -f /tmp/environment.yml
  19 |     RUN python main.py
  20 | >>> RUN micromamba remove -f -y django
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba remove -f -y django" did not complete successfully: exit code: 1
```

**Comment by maresb** [comment] 2023-05-03 12:06
The `micromamba remove` command fails because in your `environment.yml` you are installing `django` as a pip dependency, so it's not conda-managed. Usually one only uses pip dependencies for packages which are either private or not yet on conda-forge. But `django` is definitely installable with conda-forge.

If you copy the environment from one stage to another in order to minimize the image size, you should make sure the full directory path remains the same. Also, make sure you add the environment's `bin/` directory to `PATH`. Note that while this usually works, it is not officially recommended or supported.

I'm closing this issue now, since it seems that the original problem is solved, and this thread is veering off-topic. If you have further issues, please open a new thread with a detailed report of the expected vs observed behavior, describe your attempts at solving the problem, and provide a minimal example of how to reproduce any failures.

**Closed by maresb** 2023-05-03 12:06 UTC
