### ISSUE TITLE
python not found on Singularity

### ISSUE THREAD

**Issue by avirupdas55** [mamba-org/micromamba-docker#367] opened 2023-08-29 16:03 UTC
This is the Dockerfile I have used to build the image:

```
  FROM mambaorg/micromamba:1.5-focal-cuda-11.3.1
  USER root
  RUN apt update && apt install -y --allow-unauthenticated wget git vim build-essential glibc-source
  ARG DEBIAN_FRONTEND=noninteractive

  ENV HOME /mnt/iusers01/sk01/my_uid
  ARG UID
  RUN useradd -u $UID --create-home my_uid -o

  RUN micromamba install -y -n base -c conda-forge\
         python=3.10.8 \
         pytorch \
         ecole \
         pytorch_geometric \
         pyscipopt && \
      micromamba clean --all --yes

  RUN echo 'set editing-mode vi' >> $HOME/.inputrc
  RUN echo 'set keymap vi' >> $HOME/.inputrc
```

I am getting the following error while submitting my job to a cluster:

`/.singularity.d/actions/exec: 21: exec: python: not found `

The job file executes this: `singularity exec --no-home docker://my_docker_image python -m train --model_type 'vae' --instance 'IS' `

However, it works fine when I run it on an interactive session with:

`singularity run --nv --no-home docker://my_docker_image` and `python -m train --model_type 'vae' --instance 'IS' `

Any help would be really appreciated!

**Comment by wholtz** [comment] 2023-08-29 16:07
Closing as this is a duplicate of an existing issue --  https://github.com/mamba-org/micromamba-docker/issues/155

**Closed by wholtz** 2023-08-29 16:07 UTC
