### ISSUE TITLE
`Permission denied` and `No such file or directory`

### ISSUE THREAD

**Issue by nick-youngblut** [mamba-org/micromamba-docker#261] opened 2023-02-07 21:50 UTC
I'm using the dockerfile code as show in [Adding micromamba to an existing Docker image](https://github.com/mamba-org/micromamba-docker#adding-micromamba-to-an-existing-docker-image) from the README, but I've change the 2nd `FROM` to  `FROM gitpod/workspace-base` and the micromamba install section to:

```
ARG MAMBA_DOCKERFILE_ACTIVATE=1
COPY --chown=gitpod:gitpod env.yaml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml \
  && micromamba clean --all --yes
```

If I don't include `USER root` after the 2nd `FROM`, then I get the following error:

```
> [linux/amd64 stage-1  9/12] RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh   && /usr/local/bin/_dockerfile_setup_root_prefix.sh:
 #0 0.100 /usr/local/bin/_dockerfile_initialize_user_accounts.sh: line 5: /root/.bashrc: Permission denied
```

If I include `USER root` after the 2nd `FROM`, then I get the following error:

```
 > [linux/arm64 stage-1 11/12] RUN micromamba install -y -n base -f /tmp/env.yaml   && micromamba clean --all --yes :
#0 0.131 /usr/local/bin/_activate_current_env.sh: line 8: /bin/micromamba: No such file or directory
#0 0.173 /usr/local/bin/_activate_current_env.sh: line 35: /usr/bin/micromamba: No such file or directory
```

**Comment by nick-youngblut** [comment] 2023-02-07 21:52
More generally, why wouldn't one just use `RUN curl micro.mamba.pm/install.sh | bash` if they want to add micromamba to an existing Docker image?

**Comment by wholtz** [comment] 2023-02-07 22:48
Hi @nick-youngblut - thank you for you interest in micromamba. 

Can you please post your Dockerfile (with both possible `USER root` commands, but the second one commented out)? I tried to generate what I think you have for your Dockerfile, but I'm not getting the error messages you posted.

As for why not doing `RUN curl micro.mamba.pm/install.sh | bash`? That normal install isn't docker centric, so you'll be missing scripts and an entrypoint that ensure that the `micromamba` shell function is loaded in a docker context and that the hooks for automatically activating conda environments are in place. Additionally, if you want a reproducible container build, you want to use a method that specifies the version of micromamba being installed.

**Comment by nick-youngblut** [comment] 2023-02-09 03:26
Thanks @wholtz for the quick response! My dockerfile:

```
FROM mambaorg/micromamba:1.3.0 as micromamba

FROM gitpod/workspace-base

USER root    # comment-out if necessary 

ARG MAMBA_USER=mamba
ARG MAMBA_USER_ID=1000
ARG MAMBA_USER_GID=1000
ENV MAMBA_USER=$MAMBA_USER
ENV MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_EXE="/bin/micromamba"

COPY --from=micromamba "$MAMBA_EXE" "$MAMBA_EXE"
COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_shell.sh /usr/local/bin/_dockerfile_shell.sh
COPY --from=micromamba /usr/local/bin/_entrypoint.sh /usr/local/bin/_entrypoint.sh
COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_initialize_user_accounts.sh /usr/local/bin/_dockerfile_initialize_user_accounts.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_setup_root_prefix.sh /usr/local/bin/_dockerfile_setup_root_prefix.sh

RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh && \
    /usr/local/bin/_dockerfile_setup_root_prefix.sh

USER $MAMBA_USER

SHELL ["/usr/local/bin/_dockerfile_shell.sh"]

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]

ARG MAMBA_DOCKERFILE_ACTIVATE=1
COPY --chown=gitpod:gitpod env.yaml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml \
  && micromamba clean --all --yes
```

**Comment by maresb** [comment] 2023-02-09 04:57
@nick-youngblut I think you just need to adjust `MAMBA_USER`, `MAMBA_USER_ID`, and `MAMBA_USER_GID` for Gitpod:

```Dockerfile
ARG MAMBA_USER=gitpod
ARG MAMBA_USER_ID=33333
ARG MAMBA_USER_GID=33333
```

(You can get the necessary info by running `docker run --rm -it gitpod/workspace-base id -a`.)

@wholtz, I think we are missing a `USER root` above the `RUN` command in the docs, as we are implicitly assuming `root` as the default user in the base image.

Ah, and also a warning: on my system, Docker interprets

```Dockerfile
USER root    # comment-out if necessary
```

as "switch to the user named `root    # comment-out if necessary`.

**Comment by wholtz** [comment] 2023-02-09 16:24
I agree with @maresb's analysis. This works for me:

```Dockerfile
FROM mambaorg/micromamba:1.3.0 as micromamba

FROM gitpod/workspace-base

USER root

ARG MAMBA_USER=gitpod
ARG MAMBA_USER_ID=33333
ARG MAMBA_USER_GID=33333
ENV MAMBA_USER=$MAMBA_USER
ENV MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_EXE="/bin/micromamba"

COPY --from=micromamba "$MAMBA_EXE" "$MAMBA_EXE"
COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_shell.sh /usr/local/bin/_dockerfile_shell.sh
COPY --from=micromamba /usr/local/bin/_entrypoint.sh /usr/local/bin/_entrypoint.sh
COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_initialize_user_accounts.sh /usr/local/bin/_dockerfile_initialize_user_accounts.sh
COPY --from=micromamba /usr/local/bin/_dockerfile_setup_root_prefix.sh /usr/local/bin/_dockerfile_setup_root_prefix.sh

RUN /usr/local/bin/_dockerfile_initialize_user_accounts.sh && \
    /usr/local/bin/_dockerfile_setup_root_prefix.sh

USER $MAMBA_USER

SHELL ["/usr/local/bin/_dockerfile_shell.sh"]

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh"]

ARG MAMBA_DOCKERFILE_ACTIVATE=1
COPY --chown=gitpod:gitpod env.yaml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml \
  && micromamba clean --all --yes
```

I will update the example in the documentation to add the `USER root` that is needed when the source image has a non-root user.

@nick-youngblut - please close this issue if your problem is resolved, or report back if your builds still fail.

**Comment by wholtz** [comment] 2023-02-09 17:16
Documentation changes done in #262

**Closed** 2023-02-16 15:36 UTC
